
version: 0.1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:421835937675:task-definition/YJTask:3"
        LoadBalancerInfo:
          ContainerName: "yoonjung"
          ContainerPort: 80
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-986e38d4"]
            SecurityGroups:
              [
                "sg-055bf569ee1bc9cde",
              ]
            AssignPublicIp: "ENABLED"
